repos:
  # Уазываем для репосов в моем (belas80) гите
- id: github.com/belas80/devops-diplom-netology

  # На стороне клиентского конфига разрешите изменять workflow
  allowed_overrides: [workflow, apply_requirements, delete_source_branch_on_merge]
  allow_custom_workflows: true