apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-agent
  namespace: devops-tools
  labels:
    jenkins: jenkins-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      jenkins: jenkins-agent
  template:
    metadata:
      labels:
        jenkins: jenkins-agent
    spec:
      containers:
      - name: jenkins-agent
        image: belas80/jenkins-agent
        imagePullPolicy: Always
        ports:
          - containerPort: 22
        env:
          - name: JENKINS_AGENT_SSH_PUBKEY
            valueFrom:
              secretKeyRef:
                key: ssh_key
                name: jenkins-secrets
          - name: DOCKER_HOST
            value: tcp://localhost:2376
          - name: DOCKER_TLS_VERIFY
            value: "1"
          - name: DOCKER_CERT_PATH
            value: /certs/client
        volumeMounts:
          - mountPath: /home/jenkins/agent
            name: jenkins-agent-data
          - name: some-docker-certs-client
            mountPath: /certs/client
            readOnly: true
      - name: dind
        image: docker:dind
        securityContext:
          privileged: true
        env:
          - name: DOCKER_TLS_CERTDIR
            value: /certs
        volumeMounts:
          - name: dind-storage
            mountPath: /var/lib/docker
#          - name: some-docker-certs-ca
#            mountPath: /certs/ca
          - name: some-docker-certs-client
            mountPath: /certs/client
      volumes:
        - name: jenkins-agent-data
          persistentVolumeClaim:
            claimName: jenkins-agent-pv-claim
        - name: dind-storage
          emptyDir: {}
#        - name: some-docker-certs-ca
#          emptyDir: {}
        - name: some-docker-certs-client
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent
  namespace: devops-tools
spec:
  ports:
  # Порт сетевого балансировщика, на котором будут обслуживаться пользовательские запросы.
  - port: 2222
    name: http
    # Порт контейнера, на котором доступно приложение.
    targetPort: 22
  # Метки селектора, использованные в шаблоне подов при создании объекта Deployment.
  selector:
    jenkins: jenkins-agent
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    jenkins: jenkins-agent
  name: jenkins-agent-pv-claim
  namespace: devops-tools
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs