apiVersion: v1
kind: Service
metadata:
  name: atlantis
spec:
  type: ClusterIP
  ports:
  - name: atlantis
    port: 80
    targetPort: 4141
    nodePort: 30001
  selector:
    app: atlantis
  type: NodePort