apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: myapp
spec:
  environments:
    default:
      defaultNamespace: default
      server: https://84.201.141.69:6443
    stage:
      defaultNamespace: default
      server: https://84.201.141.69:6443
    prod:
      defaultNamespace: default
      server: https://84.201.141.69:6443
    devops-tools:
      defaultNamespace: devops-tools
      server: https://84.201.141.69:6443
      includes:
        - atlantis
        - jenkins
        - jenkins-agent
        - devops-secrets
      excludes:
        - myapp
  vars:
    external:
      - name: myapp_image_tag
        default: latest
  excludes:
    - atlantis
    - jenkins
    - jenkins-agent
    - devops-secrets
